### ISSUE TITLE
cuda memory not evenly distributed between devices

### ISSUE THREAD

**Issue by frankxyy** [BlackSamorez/tensor_parallel#71] opened 2023-04-23 06:22 UTC
The model I run is chatglm-6b. I want to run it on 2 gpus. However, during running, I found that one gpu consumes 18GB VRAM, while the other consumes 6GB, which is not evenly used.

**Comment by BlackSamorez** [comment] 2023-04-23 07:02
@frankxyy Hi!
I've never encountered it. Could you please provide the code to reproduce this issue?

**Comment by frankxyy** [comment] 2023-04-23 07:13
@BlackSamorez 
Hi! The code is: https://gist.github.com/frankxyy/f2ed19969d05c7ed718568b4badffc77

The command is: CUDA_VISIBLE_DEVICES=0,1 TMPDIR=/home/xuyangyang/tmp python3 -u infer.py --req_cnt 20 --model_name THUDM/chatglm-6b --max_new_tokens 7 --tp

**Comment by BlackSamorez** [comment] 2023-04-23 07:58
@frankxyy Maybe it's due to the fact that that the model is already on `cuda:0` when using `fp16+tesor_parallel` before the model split. That makes peak memory consumption **1.5x model size**. Still this memory should be freed when you're done with model creation.
You could try not moving to GPU before using tensor_parallel or calling `torch.cuda.empty_cache()` right after the split. The former is better because it caps peak VRAM consumption at **model size / N**, where N is number of GPUs.

**Comment by frankxyy** [comment] 2023-04-23 08:38
@BlackSamorez Hi, I have updated the code. A new error occurred:
```
Traceback (most recent call last):
  File "infer.py", line 68, in <module>
    outputs = model.generate(
  File "/home/xuyangyang/miniconda3/envs/chatglm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xuyangyang/miniconda3/envs/chatglm/lib/python3.8/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.greedy_search(
  File "/home/xuyangyang/miniconda3/envs/chatglm/lib/python3.8/site-packages/transformers/generation/utils.py", line 2294, in greedy_search
    model_kwargs = self._update_model_kwargs_for_generation(
  File "/home/xuyangyang/miniconda3/envs/chatglm/lib/python3.8/site-packages/transformers/generation/utils.py", line 737, in _update_model_kwargs_for_generation
    model_kwargs["attention_mask"] = torch.cat(
RuntimeError: Tensors must have same number of dimensions: got 4 and 2

```

**Comment by BlackSamorez** [comment] 2023-04-23 10:02
@frankxyy There's something wrong with number of dims of `attention_mask`. It's probably not a `tensor_parallel` related issue.

**Comment by BlackSamorez** [comment] 2023-04-25 17:36
I'm closing this issue, since it's probably resolved. Feel free to reopen it if you think otherwise.

**Closed by BlackSamorez** 2023-04-25 17:36 UTC
